- id: 25263d9c6764471886a958ff3683af7d
  alias: Start HomeKit
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:05
  - service: homekit.start
- id: '1574386270638'
  alias: Kitchen lights at dusk
  trigger:
  - event: sunset
    offset: -00:60:00
    platform: sun
  condition:
  - condition: state
    entity_id: light.kitchen_lights
    state: 'off'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - scene: scene.kitchen_lights_to_3
  mode: single
- id: git_webhook
  alias: Git Pull
  trigger:
    platform: webhook
    webhook_id: git_pull_2586245632
  action:
  - service: hassio.addon_restart
    data:
      addon: core_git_pull
- id: '1636608309790'
  alias: Porch light -  off when all home + 15min
  description: ''
  trigger:
  - platform: state
    entity_id: group.family_presence_detection
    for:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
    from: not_home
    to: home
  condition: []
  action:
  - type: turn_off
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  mode: restart
- id: '1636608414451'
  alias: Porch Light - On at dusk -30m
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30
  condition:
  - condition: state
    entity_id: group.family_presence_detection
    state: not_home
  action:
  - type: turn_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  mode: restart
