# Automations

## Start HomeKit after Z-Wave network is up and ready (otherwise entities may not be added to HomeKit)
  - alias: 'Start HomeKit'
    trigger:
      - platform: event
        event_type: zwave.network_ready
      - platform: event
        event_type: zwave.network_complete
      - platform: event
        event_type: zwave.network_complete_some_dead
    action:
      - service: homekit.start