- id: 25263d9c6764471886a958ff3683af7d
  alias: Start HomeKit
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:05
  - service: homekit.start
- id: '1574386270638'
  alias: Kitchen lights at dusk
  trigger:
  - event: sunset
    offset: -00:60:00
    platform: sun
  condition:
  - condition: state
    entity_id: light.kitchen_lights
    state: 'off'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - scene: scene.kitchen_lights_to_15
  mode: single
- id: git_webhook
  alias: Git Pull
  trigger:
    platform: webhook
    webhook_id: git_pull_2586245632
  action:
  - service: hassio.addon_restart
    data:
      addon: core_git_pull
- id: '1636608309790'
  alias: Porch light -  off when all home + 15min after 8pm
  description: ''
  trigger:
  - platform: state
    entity_id: group.family_presence_detection
    for:
      hours: 0
      minutes: 15
      seconds: 0
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.front_door_porch_light_automation
    state: 'on'
  - condition: time
    after: '20:00:00'
  action:
  - type: turn_off
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.front_door_porch_light_automation
  mode: restart
- id: '1636608414451'
  alias: Porch Light - On at dusk -30m
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30
  condition:
  - condition: state
    entity_id: group.family_presence_detection
    state: not_home
  action:
  - type: turn_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.front_door_porch_light_automation
  mode: restart
- id: '1636961601542'
  alias: Garage Door Opens = Garage Lights On
  description: ''
  trigger:
  - platform: device
    device_id: 4362bfa413b1f2cf60e12e02ab892491
    domain: cover
    entity_id: cover.opengarage
    type: opening
  - platform: device
    device_id: 4362bfa413b1f2cf60e12e02ab892491
    domain: cover
    entity_id: cover.opengarage
    type: opened
  condition:
  - condition: device
    type: is_off
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  - condition: time
    after: '12:00:00'
  action:
  - type: turn_on
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  mode: restart
- id: '1637312306098'
  alias: Low Battery Detection
  description: ''
  use_blueprint:
    path: Sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      exclude:
        entity_id: []
        device_id:
        - b1703148bf9271629229093fb2992ccf
        - e509a7fbf9cd5b73e1d765b532047e83
      actions:
      - service: notify.mobile_app_chris_s_iphone
        data:
          message: '{{sensors}} is at or below 20% battery'
      day: 7
- id: '1637312436126'
  alias: Entryway Garage Door Opens = Turn On Garage Light
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 4ceb4559025ffbbcccbdd40168d614c3
    entity_id: binary_sensor.open_close_xs_sensor_access_control_window_door_is_open
    domain: binary_sensor
  condition:
  - condition: device
    type: is_off
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  - condition: device
    device_id: 4362bfa413b1f2cf60e12e02ab892491
    domain: cover
    entity_id: cover.opengarage
    type: is_closed
  action:
  - type: turn_on
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.garage_light_automation
  mode: restart
- id: '1637837868067'
  alias: Entryway Garage Door Closes = Turn Off If Turned On By Automation
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 4ceb4559025ffbbcccbdd40168d614c3
    entity_id: binary_sensor.open_close_xs_sensor_access_control_window_door_is_open
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: input_boolean.garage_light_automation
    state: 'on'
  action:
  - type: turn_off
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.garage_light_automation
  mode: single
- id: '1638003982512'
  alias: Web UI Notifications to HA app
  description: ''
  use_blueprint:
    path: EPMatt/persistent_notification_to_mobile.yaml
    input:
      mobile_notify_service: mobile_app_chris_s_iphone
- id: '1638004070255'
  alias: Web UI Notifications to HA app
  description: ''
  use_blueprint:
    path: EPMatt/persistent_notification_to_mobile.yaml
    input:
      mobile_notify_service: mobile_app_chris_s_iphone
- id: '1638004278746'
  alias: New Automation
  description: ''
  use_blueprint:
    path: EPMatt/persistent_notification_to_mobile.yaml
    input:
      mobile_notify_service: mobile_app_chris_s_iphone
- id: '1638004546075'
  alias: Water Detected = Send HA app notification
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 7fc49e2c9a338e32bf47fd916df3af11
    entity_id: binary_sensor.garage_wh_water_leak_sensor_water_alarm_water_leak_detected
    domain: binary_sensor
  - type: moist
    platform: device
    device_id: 7762a17897742b14981c4446f0db836f
    entity_id: binary_sensor.washing_machine_water_leak_sensor_water_alarm_water_leak_detected
    domain: binary_sensor
  - type: moist
    platform: device
    device_id: f29bae01a48b0cbc9ba42ac0e1d44639
    entity_id: binary_sensor.half_bath_water_leak_sensor_water_alarm_water_leak_detected
    domain: binary_sensor
  - type: moist
    platform: device
    device_id: 415921375f059bd1b36aa784a880bbac
    entity_id: binary_sensor.hvac_water_leak_sensor_water_alarm_water_leak_detected
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_chris_s_iphone
    data:
      title: Water Leak Detected
      message: Water leak has been detected at the {{trigger.name}}
      data:
        push:
        sound:
          name: US-EN-Alexa-Water-Detected-Generic.wav
          critical: 1
          volume: 1
  mode: restart
- id: '1638155702390'
  alias: Send Web UI persistent notifications to Mobile Devices
  description: ''
  use_blueprint:
    path: EPMatt/persistent_notification_to_mobile.yaml
    input:
      mobile_notify_service: mobile_app_chris_s_iphone
- id: '1638166098873'
  alias: Garage Lights - Double Tap On = Keep Lights On (Ignore Door Closing)
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      label: Scene 001
      device_id: 1d0a07e812ee93aa91b0043c6db43624
      value: KeyPressed2x
  condition:
  - condition: state
    entity_id: input_boolean.garage_light_automation
    state: 'on'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.garage_light_automation
  mode: restart
- id: '1638178707780'
  alias: 'Front Door Opens, Porch Light is On, and Living Room Light is Off = Turn
    On Entryway Light '
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: f126809c8323322a161ae8c08b694694
    entity_id: binary_sensor.front_door_open_close_access_control_window_door_is_open
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - condition: device
    type: is_off
    device_id: cb1c7b2a369c4d2ea064a7b7fe5010f4
    entity_id: switch.living_room_lights
    domain: switch
  action:
  - type: turn_on
    device_id: f4678b7b4fd9d823f13b7131655fa99b
    entity_id: light.entryway_lights
    domain: light
  mode: single
- id: '1638178895797'
  alias: Front Door Opens After Dusk, Porch Light is Off = Turn On Porch Light
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: f126809c8323322a161ae8c08b694694
    entity_id: binary_sensor.front_door_open_close_access_control_window_door_is_open
    domain: binary_sensor
  condition:
  - condition: device
    type: is_off
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - condition: sun
    after: sunset
    after_offset: -00:30:00
  - condition: state
    entity_id: input_boolean.front_door_porch_light_automation
    state: 'off'
  action:
  - type: turn_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  mode: restart
- id: '1638238833412'
  alias: Entryway Garage Door Opens, Porch Light is On, and Living Room Light is Off
    = Turn On Entryway Light
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 4ceb4559025ffbbcccbdd40168d614c3
    entity_id: binary_sensor.open_close_xs_sensor_access_control_window_door_is_open
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - condition: device
    type: is_off
    device_id: cb1c7b2a369c4d2ea064a7b7fe5010f4
    entity_id: switch.living_room_lights
    domain: switch
  action:
  - type: turn_on
    device_id: f4678b7b4fd9d823f13b7131655fa99b
    entity_id: light.entryway_lights
    domain: light
  mode: restart
- id: '1638487674206'
  alias: Front Door Closes After Dusk, Porch Light is On = Turn Off Porch Light After
    Delay
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: f126809c8323322a161ae8c08b694694
    entity_id: binary_sensor.front_door_open_close_access_control_window_door_is_open
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - condition: sun
    after: sunset
    after_offset: -00:30:00
  - condition: state
    entity_id: input_boolean.front_door_porch_light_automation
    state: 'off'
  action:
  - type: turn_off
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  mode: restart
- id: '1638516525616'
  alias: Send Web UI Persistent Notifications to Mobile Devices
  description: ''
  use_blueprint:
    path: EPMatt/persistent_notification_to_mobile.yaml
    input:
      mobile_notify_service: mobile_app_chris_s_iphone
- id: '1638848081442'
  alias: Send Web UI persistent notifications to Mobile Devices
  description: ''
  use_blueprint:
    path: EPMatt/persistent_notification_to_mobile.yaml
    input:
      mobile_notify_service: service.mobile_app_chris_s_iphone
- id: '1638848979539'
  alias: Web UI Notification to Mobile App Notification
  description: ''
  trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: persistent_notification
      service: create
  condition: []
  action:
  - service: notify.mobile_app_chris_s_iphone
    data:
      title: '{{ trigger.event.data.service_data.title }}'
      message: '{{ trigger.event.data.service_data.message }}'
      apns_headers:
        apns-collapse-id: '{{ trigger.event.data.service_data.notification_id if replace_notifications
          else "" }}'
  mode: single
- id: '1639586299863'
  alias: Grafana - HVAC - Get Image
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition: []
  action: []
  mode: restart
- id: '1640941284019'
  alias: Porch Light - Back On If Family Group Changes To Away
  description: ''
  trigger:
  - platform: state
    entity_id: group.family_presence_detection
    from: home
    to: not_home
  condition:
  - condition: sun
    after: sunset
    after_offset: '1:00:00'
  action:
  - type: turn_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.front_door_porch_light_automation
  mode: restart
