- id: 25263d9c6764471886a958ff3683af7d
  alias: Start HomeKit
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:05
  - service: homekit.start
- id: '1574386270638'
  alias: Kitchen lights at dusk
  trigger:
  - event: sunset
    offset: -00:60:00
    platform: sun
  condition:
  - condition: state
    entity_id: light.kitchen_lights
    state: 'off'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - scene: scene.kitchen_lights_to_3
  mode: single
- id: git_webhook
  alias: Git Pull
  trigger:
    platform: webhook
    webhook_id: git_pull_2586245632
  action:
  - service: hassio.addon_restart
    data:
      addon: core_git_pull
- id: '1636608309790'
  alias: Porch light -  off when all home + 15min
  description: ''
  trigger:
  - platform: state
    entity_id: group.family_presence_detection
    for:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
    from: not_home
    to: home
  condition: []
  action:
  - type: turn_off
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  mode: restart
- id: '1636608414451'
  alias: Porch Light - On at dusk -30m
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30
  condition:
  - condition: state
    entity_id: group.family_presence_detection
    state: not_home
  action:
  - type: turn_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  mode: restart
- id: '1636961601542'
  alias: Garage Door Opens = Garage Lights On
  description: ''
  trigger:
  - platform: device
    device_id: 4362bfa413b1f2cf60e12e02ab892491
    domain: cover
    entity_id: cover.opengarage
    type: opening
  - platform: device
    device_id: 4362bfa413b1f2cf60e12e02ab892491
    domain: cover
    entity_id: cover.opengarage
    type: opened
  condition:
  - condition: device
    type: is_off
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  - condition: time
    after: '12:00:00'
  action:
  - type: turn_on
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  mode: restart
- id: '1637312306098'
  alias: Low Battery Detectionm
  description: ''
  use_blueprint:
    path: Sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      exclude:
        entity_id: []
        device_id:
        - 4ceb4559025ffbbcccbdd40168d614c3
        - 7fc49e2c9a338e32bf47fd916df3af11
        - 415921375f059bd1b36aa784a880bbac
        - f29bae01a48b0cbc9ba42ac0e1d44639
        - 7762a17897742b14981c4446f0db836f
      actions:
      - service: notify.mobile_app_chris_s_iphone
        data:
          message: '{{sensors}} is at or below 20% battery'
      day: 7
- id: '1637312436126'
  alias: Entryway Garage Door Opens, turn on Garage Light
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 4ceb4559025ffbbcccbdd40168d614c3
    entity_id: binary_sensor.open_close_xs_sensor_access_control_window_door_is_open
    domain: binary_sensor
  condition:
  - condition: device
    type: is_off
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  - condition: device
    device_id: 4362bfa413b1f2cf60e12e02ab892491
    domain: cover
    entity_id: cover.opengarage
    type: is_closed
  action:
  - type: turn_on
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  mode: restart
