- id: 25263d9c6764471886a958ff3683af7d
  alias: Start HomeKit
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:05
  - service: homekit.start
- id: '1574386270638'
  alias: Kitchen lights at dusk
  trigger:
  - event: sunset
    offset: -00:60:00
    platform: sun
  condition:
  - condition: state
    entity_id: light.kitchen_lights
    state: 'off'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - scene: scene.kitchen_lights_to_15
  mode: single
- id: git_webhook
  alias: Git Pull
  trigger:
  - platform: webhook
    webhook_id: git_pull_2586245632
    allowed_methods:
    - POST
    - PUT
    local_only: false
  action:
  - service: hassio.addon_restart
    data:
      addon: core_git_pull
- id: '1636608309790'
  alias: Porch light -  off when all home + 15min after 8pm
  description: ''
  trigger:
  - platform: state
    entity_id: group.family_presence_detection
    for:
      hours: 0
      minutes: 15
      seconds: 0
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.front_door_porch_light_automation
    state: 'on'
  - condition: time
    after: '20:00:00'
  action:
  - type: turn_off
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.front_door_porch_light_automation
  mode: restart
- id: '1636608414451'
  alias: Porch Light - On at dusk -30m
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30
  condition:
  - condition: state
    entity_id: group.family_presence_detection
    state: not_home
  action:
  - type: turn_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.front_door_porch_light_automation
  mode: restart
- id: '1636961601542'
  alias: Garage Door Opens = Garage Lights On
  description: ''
  trigger:
  - platform: device
    device_id: 4362bfa413b1f2cf60e12e02ab892491
    domain: cover
    entity_id: cover.opengarage
    type: opening
  - platform: device
    device_id: 4362bfa413b1f2cf60e12e02ab892491
    domain: cover
    entity_id: cover.opengarage
    type: opened
  condition:
  - condition: device
    type: is_off
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  - condition: time
    after: '12:00:00'
  action:
  - type: turn_on
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  mode: restart
- id: '1637312306098'
  alias: Low Battery Detection
  description: ''
  use_blueprint:
    path: Sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      exclude:
        entity_id: []
        device_id:
        - b1703148bf9271629229093fb2992ccf
        - e509a7fbf9cd5b73e1d765b532047e83
      actions:
      - service: notify.ios_chriss_iphone
        data:
          message: '{{sensors}} is at or below 20% battery'
      day: 7
- id: '1637312436126'
  alias: Entryway Garage Door Opens = Turn On Garage Light
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 4ceb4559025ffbbcccbdd40168d614c3
    entity_id: binary_sensor.open_close_xs_sensor_access_control_window_door_is_open
    domain: binary_sensor
  condition:
  - condition: device
    type: is_off
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  - condition: device
    device_id: 4362bfa413b1f2cf60e12e02ab892491
    domain: cover
    entity_id: cover.opengarage
    type: is_closed
  action:
  - type: turn_on
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.garage_light_automation
  mode: restart
- id: '1637837868067'
  alias: Entryway Garage Door Closes = Turn Off If Turned On By Automation
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 4ceb4559025ffbbcccbdd40168d614c3
    entity_id: binary_sensor.open_close_xs_sensor_access_control_window_door_is_open
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: input_boolean.garage_light_automation
    state: 'on'
  action:
  - type: turn_off
    device_id: 1d0a07e812ee93aa91b0043c6db43624
    entity_id: switch.garage_lights
    domain: switch
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.garage_light_automation
  mode: single
- id: '1638003982512'
  alias: Web UI Notifications to HA app
  description: ''
  use_blueprint:
    path: EPMatt/persistent_notification_to_mobile.yaml
    input:
      mobile_notify_service: mobile_app_chris_s_iphone
- id: '1638004070255'
  alias: Web UI Notifications to HA app
  description: ''
  use_blueprint:
    path: EPMatt/persistent_notification_to_mobile.yaml
    input:
      mobile_notify_service: mobile_app_chris_s_iphone
- id: '1638004278746'
  alias: New Automation
  description: ''
  use_blueprint:
    path: EPMatt/persistent_notification_to_mobile.yaml
    input:
      mobile_notify_service: mobile_app_chris_s_iphone
- id: '1638004546075'
  alias: Water Detected = Send HA app notification
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 7fc49e2c9a338e32bf47fd916df3af11
    entity_id: binary_sensor.garage_wh_water_leak_sensor_water_alarm_water_leak_detected
    domain: binary_sensor
  - type: moist
    platform: device
    device_id: 7762a17897742b14981c4446f0db836f
    entity_id: binary_sensor.washing_machine_water_leak_sensor_water_alarm_water_leak_detected
    domain: binary_sensor
  - type: moist
    platform: device
    device_id: f29bae01a48b0cbc9ba42ac0e1d44639
    entity_id: binary_sensor.half_bath_water_leak_sensor_water_alarm_water_leak_detected
    domain: binary_sensor
  - type: moist
    platform: device
    device_id: 415921375f059bd1b36aa784a880bbac
    entity_id: binary_sensor.hvac_water_leak_sensor_water_alarm_water_leak_detected
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_chris_s_iphone
    data:
      title: Water Leak Detected
      message: Water leak has been detected at the {{device.name}}
      data:
        push:
          sound:
            name: US-EN-Alexa-Water-Detected-Generic.wav
            critical: 1
            volume: 1
  mode: restart
- id: '1638155702390'
  alias: Send Web UI persistent notifications to Mobile Devices
  description: ''
  use_blueprint:
    path: EPMatt/persistent_notification_to_mobile.yaml
    input:
      mobile_notify_service: mobile_app_chris_s_iphone
- id: '1638166098873'
  alias: Garage Lights - Double Tap On = Keep Lights On (Ignore Door Closing)
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      label: Scene 001
      device_id: 1d0a07e812ee93aa91b0043c6db43624
      value: KeyPressed2x
  condition:
  - condition: state
    entity_id: input_boolean.garage_light_automation
    state: 'on'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.garage_light_automation
  mode: restart
- id: '1638178707780'
  alias: 'Front Door Opens, Porch Light is On, and Living Room Light is Off = Turn
    On Entryway Light '
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: f126809c8323322a161ae8c08b694694
    entity_id: binary_sensor.front_door_open_close_access_control_window_door_is_open
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - condition: device
    type: is_off
    device_id: cb1c7b2a369c4d2ea064a7b7fe5010f4
    entity_id: switch.living_room_lights
    domain: switch
  action:
  - type: turn_on
    device_id: f4678b7b4fd9d823f13b7131655fa99b
    entity_id: light.entryway_lights
    domain: light
  mode: single
- id: '1638178895797'
  alias: Front Door Opens After Dusk, Porch Light is Off = Turn On Porch Light
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: f126809c8323322a161ae8c08b694694
    entity_id: binary_sensor.front_door_open_close_access_control_window_door_is_open
    domain: binary_sensor
  condition:
  - condition: device
    type: is_off
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - condition: sun
    after: sunset
    after_offset: -00:30:00
  - condition: state
    entity_id: input_boolean.front_door_porch_light_automation
    state: 'off'
  action:
  - type: turn_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  mode: restart
- id: '1638238833412'
  alias: Entryway Garage Door Opens, Porch Light is On, and Living Room Light is Off
    = Turn On Entryway Light
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 4ceb4559025ffbbcccbdd40168d614c3
    entity_id: binary_sensor.open_close_xs_sensor_access_control_window_door_is_open
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - condition: device
    type: is_off
    device_id: cb1c7b2a369c4d2ea064a7b7fe5010f4
    entity_id: switch.living_room_lights
    domain: switch
  action:
  - type: turn_on
    device_id: f4678b7b4fd9d823f13b7131655fa99b
    entity_id: light.entryway_lights
    domain: light
  mode: restart
- id: '1638487674206'
  alias: Front Door Closes After Dusk, Porch Light is On = Turn Off Porch Light After
    Delay
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: f126809c8323322a161ae8c08b694694
    entity_id: binary_sensor.front_door_open_close_access_control_window_door_is_open
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - condition: sun
    after: sunset
    after_offset: -00:30:00
  - condition: state
    entity_id: input_boolean.front_door_porch_light_automation
    state: 'off'
  action:
  - type: turn_off
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  mode: restart
- id: '1638516525616'
  alias: Send Web UI Persistent Notifications to Mobile Devices
  description: ''
  use_blueprint:
    path: EPMatt/persistent_notification_to_mobile.yaml
    input:
      mobile_notify_service: mobile_app_chris_s_iphone
- id: '1639586299863'
  alias: Grafana - HVAC - Get Image
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition: []
  action: []
  mode: restart
- id: '1640941284019'
  alias: Porch Light - Back On If Family Group Changes To Away
  description: ''
  trigger:
  - platform: state
    entity_id: group.family_presence_detection
    from: home
    to: not_home
  condition:
  - condition: sun
    after: sunset
    after_offset: '1:00:00'
  action:
  - type: turn_on
    device_id: e3be87619ce7a753fc139b121a390da2
    entity_id: switch.porch_light
    domain: switch
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.front_door_porch_light_automation
  mode: restart
- id: '1645678084022'
  alias: Disable vacuum camera update when docked
  description: ''
  use_blueprint:
    path: PiotrMachowski/disable_vacuum_camera_update_when_docked.yaml
    input:
      vacuum: vacuum.roborock_s5_max
      camera: camera.xiaomi_cloud_map_extractor
- id: '1646596993998'
  alias: Motion - Upstairs Bathroom Light - Normal Light
  description: Turn on if after sundown and before midnight
  trigger:
  - type: motion
    platform: device
    device_id: c4e05f87790f403d5cd1fca49f0adf8a
    entity_id: 0e3c79d4d714f1df83c2e57b2cc28838
    domain: binary_sensor
  condition:
  - condition: sun
    after: sunset
  - condition: device
    type: is_off
    device_id: f716a4d5908662d57e3e03b231088098
    entity_id: light.upstairs_bathroom_light
    domain: light
  - condition: time
    before: 00:00:00
    weekday:
    - sun
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
  action:
  - type: turn_on
    device_id: f716a4d5908662d57e3e03b231088098
    entity_id: light.upstairs_bathroom_light
    domain: light
    brightness_pct: 50
  mode: restart
- id: '1646644319478'
  alias: Motion - Upstairs Bathroom Light - Nightlight
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: b2259036d5cb481cd837164f924fb7b6
    entity_id: binary_sensor.upstairs_bathroom_sensor_home_security_motion_detection
    domain: binary_sensor
  condition:
  - condition: time
    before: 00:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    after: 00:00:00
  - condition: sun
    before: sunrise
  - condition: device
    type: is_off
    device_id: f716a4d5908662d57e3e03b231088098
    entity_id: light.upstairs_bathroom_light
    domain: light
  action:
  - type: turn_on
    device_id: f716a4d5908662d57e3e03b231088098
    entity_id: light.upstairs_bathroom_light
    domain: light
    brightness_pct: 20
  mode: restart
- id: '1646723972912'
  alias: Humidity - Upstairs Bathroom Fan On
  description: ''
  trigger:
  - type: humidity
    platform: device
    device_id: b2259036d5cb481cd837164f924fb7b6
    entity_id: sensor.upstairs_bathroom_sensor_humidity
    domain: sensor
    above: 60
  condition: []
  action:
  - type: turn_on
    device_id: 974156a1a00d048ba59b19a94af2a6be
    entity_id: switch.upstairs_bathroom_fan
    domain: switch
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.upstairs_bathroom_fan_automation
  mode: single
- id: '1646724050645'
  alias: Humidity - Upstairs Bathroom Fan Off
  description: ''
  trigger:
  - type: humidity
    platform: device
    device_id: b2259036d5cb481cd837164f924fb7b6
    entity_id: sensor.upstairs_bathroom_sensor_humidity
    domain: sensor
    below: 59
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.upstairs_bathroom_fan_automation
    state: 'on'
  action:
  - type: turn_on
    device_id: 974156a1a00d048ba59b19a94af2a6be
    entity_id: switch.upstairs_bathroom_fan
    domain: switch
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.upstairs_bathroom_fan_automation
  - type: turn_off
    device_id: 974156a1a00d048ba59b19a94af2a6be
    entity_id: switch.upstairs_bathroom_fan
    domain: switch
  mode: single
- id: '1661140476685'
  alias: Water Detected = Send HA app notification (Duplicate)
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 7fc49e2c9a338e32bf47fd916df3af11
    entity_id: binary_sensor.garage_wh_water_leak_sensor_water_alarm_water_leak_detected
    domain: binary_sensor
  - type: moist
    platform: device
    device_id: 7762a17897742b14981c4446f0db836f
    entity_id: binary_sensor.washing_machine_water_leak_sensor_water_alarm_water_leak_detected
    domain: binary_sensor
  - type: moist
    platform: device
    device_id: f29bae01a48b0cbc9ba42ac0e1d44639
    entity_id: binary_sensor.half_bath_water_leak_sensor_water_alarm_water_leak_detected
    domain: binary_sensor
  - type: moist
    platform: device
    device_id: 415921375f059bd1b36aa784a880bbac
    entity_id: binary_sensor.hvac_water_leak_sensor_water_alarm_water_leak_detected
    domain: binary_sensor
  - platform: state
    entity_id:
    - binary_sensor.garage_wh_water_leak_sensor_water_alarm_water_leak_detected
    from: 'false'
    to: 'true'
  condition: []
  action:
  - service: notify.mobile_app_chris_s_iphone
    data:
      title: Water Leak Detected
      message: Water leak has been detected at the {{device.name}}
      data:
        push:
          sound:
            name: US-EN-Alexa-Water-Detected-Generic.wav
            critical: 1
            volume: 1
  mode: restart
- id: '1661142029824'
  alias: Water Leak Notification - Blueprint
  description: ''
  use_blueprint:
    path: TurtleFX/leak-detector-notifier.yaml
    input:
      actions:
      - service: notify.ios_chriss_iphone
        data:
          title: Leak Detected
          message: '{{ trigger.event.data.new_state.attributes.friendly_name }} has
            detected a leak!'
          data:
            push:
              sound:
                name: US-EN-Alexa-Water-Detected-Generic.wav
                critical: 1
                volume: 1
- id: '1663035327991'
  alias: Leak detection & notifier 2
  description: ''
  use_blueprint:
    path: bbbenji/leak-detector-notifier.yaml
    input:
      notify_device: e509a7fbf9cd5b73e1d765b532047e83
- id: '1677303092503'
  alias: Smoke Alert
  description: ''
  use_blueprint:
    path: user-x-adm/smoke-alert-en.yaml
    input:
      sensor:
      - binary_sensor.smoke_co_andrew_smoke_detected
      - binary_sensor.smoke_co_chris_smoke_detected
      - binary_sensor.smoke_co_master_smoke_detected
- id: '1677303703687'
  alias: Smoke Detector Notification
  description: ''
  trigger:
  - type: smoke
    platform: device
    device_id: 769df9de0132834466382d98fb7c81f1
    entity_id: binary_sensor.smoke_co_chris_smoke_detected
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: 3446fbd11ae0d751f61ace6f6799bf25
    entity_id: binary_sensor.smoke_co_andrew_smoke_detected
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: b186d9a2a9cda67cb8a42a50a6e4c6cb
    entity_id: binary_sensor.smoke_co_master_smoke_detected
    domain: binary_sensor
  condition: []
  action:
  - service: notify.notify
    data:
      target: e509a7fbf9cd5b73e1d765b532047e83
      title: FIRE / SMOKE DETECTED
      message: '{{ trigger.to_state.name }}'
  mode: single
- id: '1709173532025'
  alias: Vent Garage
  description: Only if door is open
  trigger:
  - platform: state
    entity_id:
    - input_button.vent_garage_door
  condition:
  - condition: state
    entity_id: cover.opengarage
    attribute: custom_ui_state_card
    state: open
  action:
  - service: cover.close_cover
    metadata: {}
    data: {}
    target:
      entity_id: cover.opengarage
  - delay:
      hours: 0
      minutes: 0
      seconds: 12
      milliseconds: 0
  - service: cover.open_cover
    metadata: {}
    data: {}
    target:
      entity_id: cover.opengarage
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: cover.close_cover
    metadata: {}
    data: {}
    target:
      entity_id: cover.opengarage
  mode: single
