- alias: Start HomeKit
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:05
  - service: homekit.start
  id: 25263d9c6764471886a958ff3683af7d
- id: '1574386270638'
  alias: Kitchen lights at dusk
  description: ''
  trigger:
  - event: sunset
    offset: '-30'
    platform: sun
  condition:
  - condition: state
    entity_id: light.kitchen_lights
    state: 'off'
  action:
  - scene: scene.kitchen_lights_to_3
