homeassistant:
  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation

  # metric for Metric, imperial for Imperial
  unit_system: imperial

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

  # Save data to Influxfor use in graphs
influxdb:
  api_version: 2
  host: 10.0.0.80
  port: 8086
  ssl: false
  organization: baa8bcc736bfe0a0
  token: !secret influxtoken
  bucket: home-assistant

opnsense:
  url: https://10.0.0.1:7443/api
  api_secret: !secret opnsenseapisecret
  api_key: !secret opnsenseapikey

# Use Postgres for logging
recorder: !include recorder-postgres.yaml

# Log Viewer add on
logger:
  default: warning
  logs:
    homeassistant.components.homekit: debug
    pyhap: debug

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Enable Energy Dashboard
energy:

# HACS plug-in - remote syslog
remote_syslog:

# Enables helpers
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
counter:
timer:

# shell_command
shell_command: !include shell_command.yaml

#customizer:
#  custom_ui: local

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
#   base_url: example.duckdns.org:8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.85
    - 10.253.0.50
    - 10.0.0.80
  login_attempts_threshold: 3
  ip_ban_enabled: false

api:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# iOS Component
ios:

# Enable Alexa through haaska
alexa:
  smart_home:

# HomeKit:
homekit: !include homekit.yaml

# Enables emulated-hue so Alexa can control devices
## Devices are not included automatically for more control
## To add a device, add emulated_hue: true to the entity in customize.yaml
emulated_hue:
  expose_by_default: false

# Real Hue bridge
hue:
  bridges:
    - host: 10.0.0.112

# Add links to sidebar
panel_iframe: !include panel_iframe.yaml

# Cameras
camera: !include cameras.yaml

# Sensors
sensor: !include sensors.yaml

# Switches
switch: !include  switches.yaml

# Packages Directory
#packages: !include_dir_named packages


# Nextcloud

nextcloud:
  url: https://nc.chrisvick.com
  username: cvick
  password: !secret nextcloud

# Text to speech
#tts:
#  - platform: google_translate
#    service_name: google_say

# System Health
system_health:

mobile_app:

# Cloud
#cloud:

# Groups
group: !include groups.yaml

# Automations
automation: !include automations.yaml

# Scripts
script: !include scripts.yaml

# Scenes
scene: !include scenes.yaml

# Enable Lovelace YAML mode
lovelace:
  mode: yaml

# Custom Devices

## Wemo Plugs
wemo: !include wemo.yaml

## Thermostats (Honeywell 9000)

# climate 1:
#   - platform: honeywell
#     username: !secret honeywell_username
#     password: !secret honeywell_pass
#     scan_interval: 600

# cover: !include covers.yaml