title: Home Assistant
resources: !include lovelace/resources.yaml
views:
  - path: default_view
    title: Home
    badges:
      - binary_sensor.updater
      - person.chris
      - sensor.rtorrent_down_speed
      - sensor.rtorrent_up_speed
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
      - sensor.dark_sky_precip_probability
      - sun.sun
      - sensor.plex

    cards:
      - type: entities
        entities:
          - light.hue_color_lamp_3
          - light.hue_color_lamp_2
          - light.hue_color_lamp_1
          - light.hue_color_lamp_4
        title: Chris's Room
        show_header_toggle: true
      
      - type: entities
        entities:
          - switch.living_room_lights
          - light.couch_light
          - light.kitchen_lights
          - switch.porch_light
        title: Downstairs
        show_header_toggle: true
      
      - type: entities
        entities:
          - switch.lights
          - switch.stairs_light
        title: Upstairs
        show_header_toggle: true

      - type: entities
        entities:
          - switch.garage_lights
          - cover.opengarage
          - entity: binary_sensor.opengarage_vehicle
            name: Car Status
            icon: hass:car
          - entity: sensor.opengarage_dist
            name: Distance
            icon: mdi:arrow-down-thick
          - entity: sensor.opengarage_temp
            name: Temperature
            icon: mdi:thermometer
          - entity: sensor.opengarage_humid
            name: Humidity
            icon: mdi:water-percent
          - entity: sensor.opengarage_rssi
            name: WiFi Signal Strength
        title: Garage
        show_header_toggle: false

      - type: entities
        entities:
          - entity: binary_sensor.front_door_open_close_access_control_window_door_is_open
            name: Front Door
          - entity: binary_sensor.open_close_xs_sensor_access_control_window_door_is_open
            name: Entryway Garage Door
        title: Door Sensors

      - type: entities
        entities:
          - entity: binary_sensor.garage_wh_water_leak_sensor_water_alarm_water_leak_detected
            name: Water Heater
          - entity: binary_sensor.washing_machine_water_leak_sensor_water_alarm_water_leak_detected
            name: Washing Machine
          - entity: binary_sensor.half_bath_water_leak_sensor_water_alarm_water_leak_detected
            name: Half Bath Closet
          - entity: binary_sensor.hvac_water_leak_sensor_water_alarm_water_leak_detected
            name: HVAC
        title: Water Leak Sensors

      - type: picture-entity
        entity: camera.grafana_temp

      - type: entities
        entities:
          - scene.kitchen_lights_to_3
          - scene.close_the_garage_door
          - scene.open_the_garage_door
        title: Scenes

      #- type: entities
      #  entities:
      #    - entity: sensor.cox_utilization
      #      icon: mdi:percent
      #    - entity: sensor.cox_time_left
      #      icon: mdi:calendar-clock
      #    - entity: sensor.cox_avg_gb_current
      #      icon: mdi:chart-line
      #    - entity: sensor.cox_avg_gb_remaining
      #      icon: mdi:chart-line-stacked
      #  show_header_toggle: false
      #  title: Cox Internet Usage

      # Denon Receiver & HEOS
      - type: entities
        entities:
          - media_player.living_room
          - media_player.living_room_2
        title: Living Room AVR

  - path: thermostats_tab
    title: Thermostats
    badges: []
    cards:
      - type: thermostat
        entity: climate.downstairs
      - type: thermostat
        entity: climate.upstairs
      - type: picture-entity
        entity: camera.grafana_temp

  - path: floors
    title: Floors
    badges: []
    cards:
      - type: entities
        entities:
          - switch.living_room_lights
          - light.kitchen_lights
          - switch.porch_light
          - switch.stairs_light
          - light.couch_light
          - climate.downstairs
        title: Downstairs
        show_header_toggle: true
      - type: entities
        entities:
          - switch.lights
          - climate.upstairs
        title: Upstairs
        show_header_toggle: true
      - type: entities
        entities:
          - switch.garage_lights
        title: Garage

#  - !include lovelace/glance-coronavirus.yaml

  - !include lovelace/nextcloud.yaml

  - !include lovelace/coxusage.yaml

  - !include lovelace/printer-xp820.yaml

  - !include lovelace/pi-hole.yaml

  - !include lovelace/water-leak-sensors.yaml