title: Home Assistant
resources: !include lovelace/resources.yaml
views:
  - path: default_view
    title: Home
    badges:
      - binary_sensor.updater
      - person.chris
      - sensor.rtorrent_down_speed
      - sensor.rtorrent_up_speed
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
      - sensor.dark_sky_precip_probability
      - sun.sun
      - sensor.plex
      #- entity: sensor.us_coronavirus_confirmed
      #- entity: sensor.us_coronavirus_recovered
      #- entity: sensor.us_coronavirus_deaths
      #- entity: sensor.us_coronavirus_current
      #- entity: sensor.worldwide_coronavirus_confirmed
      #- entity: sensor.worldwide_coronavirus_recovered
      #- entity: sensor.worldwide_coronavirus_deaths
      #- entity: sensor.worldwide_coronavirus_current
    cards:
      - type: entities
        entities:
          - light.hue_color_lamp_3
          - light.hue_color_lamp_2
          - light.hue_color_lamp_1
        title: Chris's Room
        show_header_toggle: true
      - type: entities
        entities:
          - switch.stairs_light
          - switch.living_room_lights
          - light.couch_light
          - light.kitchen_lights
          - switch.porch_light
        title: Downstairs
        show_header_toggle: true
      - type: entities
        entities:
          - switch.lights
          - switch.stairs_light
        title: Upstairs
        show_header_toggle: true
      #- type: entities
      #  entities:
      #    - entity: light.kitchen_lights
      #      name: Lights
      #  title: Kitchen
      #  show_header_toggle: true
      #- type: entities
      #  entities:
      #    - switch.living_room_lights
      #    - light.couch_light
      #  title: Living Room
      #  show_header_toggle: true
      #- type: entities
      #  entities:
      #    - switch.porch_light
      #  title: Outside
      #  show_header_toggle: true
      #- type: entities
      #  entities:
      #    - switch.lights
      #    - switch.living_room_lights
      #    - light.kitchen_lights
      #    - switch.porch_light
      #    - switch.stairs_light
      #    - light.couch_light
      #  title: Lights
      #  show_header_toggle: true
      #- type: entities
      #  entities:
      #    - switch.living_room_lights
      #    - light.kitchen_lights
      #    - switch.porch_light
      #    - switch.stairs_light
      #    - light.couch_light
      #  title: First Floor
      #  show_header_toggle: true
      #- type: thermostat
      #  entity: climate.downstairs
      #- type: entities
      #  entities:
      #    - switch.lights
      #  title: Second Floor
      #  show_header_toggle: true
      #- type: thermostat
      #  entity: climate.upstairs
      - type: entities
        entities:
          - cover.opengarage
          - entity: binary_sensor.opengarage_vehicle
          - entity: sensor.opengarage_dist
          - entity: sensor.opengarage_temp
          - entity: sensor.opengarage_humid
          - entity: sensor.opengarage_rssi
        title: Garage
        show_header_toggle: true

      - type: picture-entity
        entity: camera.grafana_temp
      #- type: entities
      #  entities:
      #    - light.bedroom
      #    - light.chris_s_room
      #  title: Light
      - type: entities
        entities:
          - scene.kitchen_lights_to_3
          - scene.close_the_garage_door
          - scene.open_the_garage_door
        title: Scene
      #- type: entities
      #  entities:
      #    - zwave.aeotec_zw090_zstick_gen5_us
      #  title: Z-Wave

      #- type: entities
      #  entities:
      #    - entity: sensor.cox_utilization
      #      icon: mdi:percent
      #    - entity: sensor.cox_time_left
      #      icon: mdi:calendar-clock
      #    - entity: sensor.cox_avg_gb_current
      #      icon: mdi:chart-line
      #    - entity: sensor.cox_avg_gb_remaining
      #      icon: mdi:chart-line-stacked
      #  show_header_toggle: false
      #  title: Cox Internet Usage

      # Denon Receiver & HEOS
      - type: entities
        entities:
          - media_player.living_room
          - media_player.living_room_2
        title: Living Room AVR

  - path: thermostats_tab
    title: Thermostats
    badges: []
    cards:
      - type: thermostat
        entity: climate.downstairs
      - type: thermostat
        entity: climate.upstairs
      - type: picture-entity
        entity: camera.grafana_temp
  #- path: lights_tab
  #  title: Lights
  #  badges: []
    #cards:
    #  - type: entities
    #    entities:
    #      - light.kitchen_lights
    #      - light.couch_light
    #    title: Light
    #  - type: entities
    #    entities:
    #      - switch.lights
    #      - switch.living_room_lights
    #      - switch.porch_light
    #      - switch.stairs_light
    #    title: Switch
  - path: floors
    title: Floors
    badges: []
    cards:
      - type: entities
        entities:
          - switch.living_room_lights
          - light.kitchen_lights
          - switch.porch_light
          - switch.stairs_light
          - light.couch_light
          - climate.downstairs
        title: Downstairs
        show_header_toggle: true
      #- type: thermostat
      #  entity: climate.downstairs
      - type: entities
        entities:
          - switch.lights
          - climate.upstairs
        title: Upstairs
        show_header_toggle: true
      #- type: thermostat
      #  entity: climate.upstairs

#  - !include lovelace/glance-coronavirus.yaml

  - !include lovelace/nextcloud.yaml

  - !include lovelace/coxusage.yaml

  - !include lovelace/printer-xp820.yaml

  - !include lovelace/pi-hole.yaml

  - !include lovelace/water-leak-sensors.yaml